# Generated by Django 5.2.6 on 2025-09-18 12:15

import achat.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', achat.models.CustomUserManager()),
            ],
        ),
    ]
