# Generated by Django 5.2.6 on 2025-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
